# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6137d790c3fd8b79107d3350be9b06d655ef38fdd0c37497fd47fbe2d67f54d3a6dd546040a7dd8bee4dc9d5f41a4060ca923b545fd0db5cbc0219e3a429e66d

test:
  secret_key_base: e02a6efc578d8d149f5e638535562de1e5c295ab8ff19dc0b71f1a34073cee520847d9221a074cc463be0c04552f4b8f0bce901f227489a6fbaeb17908be1db0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
